[tool.poetry]
name = "monarch-mapping-commons"
version = "0.1.0"
description = "Mapping Commons for the Monarch Initiative knowledge graph"
authors = ["glass-ships <glass.ships@outlook.com>"]
readme = "README.md"
# packages = [{include = "monarch_mapping_commons"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.0"
curies = "^0.5.3"
sssom = "^0.3.28"
j2cli = "^0.3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
