curie_map:
  ICD10CM: http://purl.bioontology.org/ontology/ICD10CM/
  NCI: http://purl.obolibrary.org/obo/NCIT_
  MONDO: http://purl.obolibrary.org/obo/MONDO_
  owl: http://www.w3.org/2002/07/owl#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  skos: http://www.w3.org/2004/02/skos/core#
  sssom: http://w3id.org/sssom/
  ICD10: http://icd10data.org/
