# Basic QC workflow

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sssom_validation:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5.3
    steps:
      #- name: Install latest SSSOM
      #  env:
      #    DEFAULT_BRANCH: main
      #  run: pip install --upgrade pip && pip install -U sssom phenio-toolkit

      - uses: actions/checkout@v4

      - name: Prepare mappings
        env:
          DEFAULT_BRANCH: main
        run: |
          make RUN="" GH_ACTION=true mappings 

      - name: Run Mapping QC checks
        env:
          DEFAULT_BRANCH: main
        run: make test
